server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-passtrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
    - argocd-test.ddns.net
    tls:
    - hosts:
      - argocd-test.ddns.net
      secretName: argocd-secret
  service:
    servicePortHttps: 443
  extraArgs:
  - --insecure
installCRDs: false
