apiVersion: cert-manager.io/v1alpha2

kind:   ClusterIssuer

metadata:
  name: letsencrypt-prod

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: vuthymay38@gmail.com
    privateKeySecretRef:
      name: aws-acme-prod
    solvers:
    - http01:
        ingress:
          class : nginx
